# Generated by Django 5.2.5 on 2025-10-27 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EdaSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(max_length=500)),
                ('row_count', models.IntegerField(blank=True, null=True)),
                ('column_count', models.IntegerField(blank=True, null=True)),
                ('insights', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EdaChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(choices=[('histogram', 'Histogram'), ('bar', 'Bar Chart'), ('correlation', 'Correlation Heatmap'), ('pairplot', 'Pair Plot'), ('boxplot', 'Box Plot'), ('missing', 'Missing Value Matrix'), ('scatter', 'Scatter Plot'), ('distribution', 'Distribution Plot')], max_length=50)),
                ('chart_path', models.CharField(max_length=500)),
                ('column_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charts', to='eda.edasession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
